-- V6: Backfill flag_country and flag_url for existing ship positions using MMSI MID lookup.
-- This is a one-time migration; new data will be enriched in-stream by ShipEnricher.
-- NOTE: Run off-peak — this may be slow on large tables. Consider batching.

WITH mid_countries (mid, country_code, country_name, flag_url) AS (
    VALUES
        ('201', 'AL', 'Albania',                             'https://flagcdn.com/h80/al.png'),
        ('202', 'AD', 'Andorra',                             'https://flagcdn.com/h80/ad.png'),
        ('203', 'AT', 'Austria',                             'https://flagcdn.com/h80/at.png'),
        ('204', 'PT', 'Azores',                              'https://flagcdn.com/h80/pt.png'),
        ('205', 'BE', 'Belgium',                             'https://flagcdn.com/h80/be.png'),
        ('206', 'BY', 'Belarus',                             'https://flagcdn.com/h80/by.png'),
        ('207', 'BG', 'Bulgaria',                            'https://flagcdn.com/h80/bg.png'),
        ('208', 'VA', 'Vatican City State',                  'https://flagcdn.com/h80/va.png'),
        ('209', 'CY', 'Cyprus',                              'https://flagcdn.com/h80/cy.png'),
        ('210', 'CY', 'Cyprus',                              'https://flagcdn.com/h80/cy.png'),
        ('211', 'DE', 'Germany',                             'https://flagcdn.com/h80/de.png'),
        ('212', 'CY', 'Cyprus',                              'https://flagcdn.com/h80/cy.png'),
        ('213', 'GE', 'Georgia',                             'https://flagcdn.com/h80/ge.png'),
        ('214', 'MD', 'Moldova',                             'https://flagcdn.com/h80/md.png'),
        ('215', 'MT', 'Malta',                               'https://flagcdn.com/h80/mt.png'),
        ('216', 'AM', 'Armenia',                             'https://flagcdn.com/h80/am.png'),
        ('218', 'DE', 'Germany',                             'https://flagcdn.com/h80/de.png'),
        ('219', 'DK', 'Denmark',                             'https://flagcdn.com/h80/dk.png'),
        ('220', 'DK', 'Denmark',                             'https://flagcdn.com/h80/dk.png'),
        ('224', 'ES', 'Spain',                               'https://flagcdn.com/h80/es.png'),
        ('225', 'ES', 'Spain',                               'https://flagcdn.com/h80/es.png'),
        ('226', 'FR', 'France',                              'https://flagcdn.com/h80/fr.png'),
        ('227', 'FR', 'France',                              'https://flagcdn.com/h80/fr.png'),
        ('228', 'FR', 'France',                              'https://flagcdn.com/h80/fr.png'),
        ('229', 'MT', 'Malta',                               'https://flagcdn.com/h80/mt.png'),
        ('230', 'FI', 'Finland',                             'https://flagcdn.com/h80/fi.png'),
        ('231', 'FO', 'Faroe Islands',                       'https://flagcdn.com/h80/fo.png'),
        ('232', 'GB', 'United Kingdom',                      'https://flagcdn.com/h80/gb.png'),
        ('233', 'GB', 'United Kingdom',                      'https://flagcdn.com/h80/gb.png'),
        ('234', 'GB', 'United Kingdom',                      'https://flagcdn.com/h80/gb.png'),
        ('235', 'GB', 'United Kingdom',                      'https://flagcdn.com/h80/gb.png'),
        ('236', 'GI', 'Gibraltar',                           'https://flagcdn.com/h80/gi.png'),
        ('237', 'GR', 'Greece',                              'https://flagcdn.com/h80/gr.png'),
        ('238', 'HR', 'Croatia',                             'https://flagcdn.com/h80/hr.png'),
        ('239', 'GR', 'Greece',                              'https://flagcdn.com/h80/gr.png'),
        ('240', 'GR', 'Greece',                              'https://flagcdn.com/h80/gr.png'),
        ('241', 'GR', 'Greece',                              'https://flagcdn.com/h80/gr.png'),
        ('242', 'MA', 'Morocco',                             'https://flagcdn.com/h80/ma.png'),
        ('243', 'HU', 'Hungary',                             'https://flagcdn.com/h80/hu.png'),
        ('244', 'NL', 'Netherlands',                         'https://flagcdn.com/h80/nl.png'),
        ('245', 'NL', 'Netherlands',                         'https://flagcdn.com/h80/nl.png'),
        ('246', 'NL', 'Netherlands',                         'https://flagcdn.com/h80/nl.png'),
        ('247', 'IT', 'Italy',                               'https://flagcdn.com/h80/it.png'),
        ('248', 'MT', 'Malta',                               'https://flagcdn.com/h80/mt.png'),
        ('249', 'MT', 'Malta',                               'https://flagcdn.com/h80/mt.png'),
        ('250', 'IE', 'Ireland',                             'https://flagcdn.com/h80/ie.png'),
        ('251', 'IS', 'Iceland',                             'https://flagcdn.com/h80/is.png'),
        ('252', 'LI', 'Liechtenstein',                       'https://flagcdn.com/h80/li.png'),
        ('253', 'LU', 'Luxembourg',                          'https://flagcdn.com/h80/lu.png'),
        ('254', 'MC', 'Monaco',                              'https://flagcdn.com/h80/mc.png'),
        ('255', 'PT', 'Madeira',                             'https://flagcdn.com/h80/pt.png'),
        ('256', 'MT', 'Malta',                               'https://flagcdn.com/h80/mt.png'),
        ('257', 'NO', 'Norway',                              'https://flagcdn.com/h80/no.png'),
        ('258', 'NO', 'Norway',                              'https://flagcdn.com/h80/no.png'),
        ('259', 'NO', 'Norway',                              'https://flagcdn.com/h80/no.png'),
        ('261', 'PL', 'Poland',                              'https://flagcdn.com/h80/pl.png'),
        ('262', 'ME', 'Montenegro',                          'https://flagcdn.com/h80/me.png'),
        ('263', 'PT', 'Portugal',                            'https://flagcdn.com/h80/pt.png'),
        ('264', 'RO', 'Romania',                             'https://flagcdn.com/h80/ro.png'),
        ('265', 'SE', 'Sweden',                              'https://flagcdn.com/h80/se.png'),
        ('266', 'SE', 'Sweden',                              'https://flagcdn.com/h80/se.png'),
        ('267', 'SK', 'Slovak Republic',                     'https://flagcdn.com/h80/sk.png'),
        ('268', 'SM', 'San Marino',                          'https://flagcdn.com/h80/sm.png'),
        ('269', 'CH', 'Switzerland',                         'https://flagcdn.com/h80/ch.png'),
        ('270', 'CZ', 'Czech Republic',                      'https://flagcdn.com/h80/cz.png'),
        ('271', 'TR', 'Turkey',                              'https://flagcdn.com/h80/tr.png'),
        ('272', 'UA', 'Ukraine',                             'https://flagcdn.com/h80/ua.png'),
        ('273', 'RU', 'Russia',                              'https://flagcdn.com/h80/ru.png'),
        ('274', 'MK', 'Macedonia',                           'https://flagcdn.com/h80/mk.png'),
        ('275', 'LV', 'Latvia',                              'https://flagcdn.com/h80/lv.png'),
        ('276', 'EE', 'Estonia',                             'https://flagcdn.com/h80/ee.png'),
        ('277', 'LT', 'Lithuania',                           'https://flagcdn.com/h80/lt.png'),
        ('278', 'SI', 'Slovenia',                            'https://flagcdn.com/h80/si.png'),
        ('279', 'RS', 'Serbia',                              'https://flagcdn.com/h80/rs.png'),
        ('301', 'AI', 'Anguilla',                            'https://flagcdn.com/h80/ai.png'),
        ('303', 'US', 'Alaska',                              'https://flagcdn.com/h80/us.png'),
        ('304', 'AG', 'Antigua and Barbuda',                 'https://flagcdn.com/h80/ag.png'),
        ('305', 'AG', 'Antigua and Barbuda',                 'https://flagcdn.com/h80/ag.png'),
        ('306', 'CW', 'Antilles',                            'https://flagcdn.com/h80/cw.png'),
        ('307', 'AW', 'Aruba',                               'https://flagcdn.com/h80/aw.png'),
        ('308', 'BS', 'Bahamas',                             'https://flagcdn.com/h80/bs.png'),
        ('309', 'BS', 'Bahamas',                             'https://flagcdn.com/h80/bs.png'),
        ('310', 'BM', 'Bermuda',                             'https://flagcdn.com/h80/bm.png'),
        ('311', 'BS', 'Bahamas',                             'https://flagcdn.com/h80/bs.png'),
        ('312', 'BZ', 'Belize',                              'https://flagcdn.com/h80/bz.png'),
        ('314', 'BB', 'Barbados',                            'https://flagcdn.com/h80/bb.png'),
        ('316', 'CA', 'Canada',                              'https://flagcdn.com/h80/ca.png'),
        ('319', 'KY', 'Cayman Islands',                      'https://flagcdn.com/h80/ky.png'),
        ('321', 'CR', 'Costa Rica',                          'https://flagcdn.com/h80/cr.png'),
        ('323', 'CU', 'Cuba',                                'https://flagcdn.com/h80/cu.png'),
        ('325', 'DM', 'Dominica',                            'https://flagcdn.com/h80/dm.png'),
        ('327', 'DO', 'Dominican Republic',                  'https://flagcdn.com/h80/do.png'),
        ('329', 'GP', 'Guadeloupe',                          'https://flagcdn.com/h80/gp.png'),
        ('330', 'GD', 'Grenada',                             'https://flagcdn.com/h80/gd.png'),
        ('331', 'GL', 'Greenland',                           'https://flagcdn.com/h80/gl.png'),
        ('332', 'GT', 'Guatemala',                           'https://flagcdn.com/h80/gt.png'),
        ('334', 'HN', 'Honduras',                            'https://flagcdn.com/h80/hn.png'),
        ('336', 'HT', 'Haiti',                               'https://flagcdn.com/h80/ht.png'),
        ('338', 'US', 'United States of America',            'https://flagcdn.com/h80/us.png'),
        ('339', 'JM', 'Jamaica',                             'https://flagcdn.com/h80/jm.png'),
        ('341', 'KN', 'Saint Kitts and Nevis',               'https://flagcdn.com/h80/kn.png'),
        ('343', 'LC', 'Saint Lucia',                         'https://flagcdn.com/h80/lc.png'),
        ('345', 'MX', 'Mexico',                              'https://flagcdn.com/h80/mx.png'),
        ('347', 'MQ', 'Martinique',                          'https://flagcdn.com/h80/mq.png'),
        ('348', 'MS', 'Montserrat',                          'https://flagcdn.com/h80/ms.png'),
        ('350', 'NI', 'Nicaragua',                           'https://flagcdn.com/h80/ni.png'),
        ('351', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('352', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('353', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('354', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('355', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('356', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('357', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('358', 'PR', 'Puerto Rico',                         'https://flagcdn.com/h80/pr.png'),
        ('359', 'SV', 'El Salvador',                         'https://flagcdn.com/h80/sv.png'),
        ('361', 'PM', 'Saint Pierre and Miquelon',           'https://flagcdn.com/h80/pm.png'),
        ('362', 'TT', 'Trinidad and Tobago',                 'https://flagcdn.com/h80/tt.png'),
        ('364', 'TC', 'Turks and Caicos Islands',            'https://flagcdn.com/h80/tc.png'),
        ('366', 'US', 'United States of America',            'https://flagcdn.com/h80/us.png'),
        ('367', 'US', 'United States of America',            'https://flagcdn.com/h80/us.png'),
        ('368', 'US', 'United States of America',            'https://flagcdn.com/h80/us.png'),
        ('369', 'US', 'United States of America',            'https://flagcdn.com/h80/us.png'),
        ('370', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('371', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('372', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('373', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('374', 'PA', 'Panama',                              'https://flagcdn.com/h80/pa.png'),
        ('375', 'VC', 'Saint Vincent and the Grenadines',    'https://flagcdn.com/h80/vc.png'),
        ('376', 'VC', 'Saint Vincent and the Grenadines',    'https://flagcdn.com/h80/vc.png'),
        ('377', 'VC', 'Saint Vincent and the Grenadines',    'https://flagcdn.com/h80/vc.png'),
        ('378', 'VG', 'British Virgin Islands',              'https://flagcdn.com/h80/vg.png'),
        ('379', 'VI', 'United States Virgin Islands',        'https://flagcdn.com/h80/vi.png'),
        ('401', 'AF', 'Afghanistan',                         'https://flagcdn.com/h80/af.png'),
        ('403', 'SA', 'Saudi Arabia',                        'https://flagcdn.com/h80/sa.png'),
        ('405', 'BD', 'Bangladesh',                          'https://flagcdn.com/h80/bd.png'),
        ('408', 'BH', 'Bahrain',                             'https://flagcdn.com/h80/bh.png'),
        ('410', 'BT', 'Bhutan',                              'https://flagcdn.com/h80/bt.png'),
        ('412', 'CN', 'China',                               'https://flagcdn.com/h80/cn.png'),
        ('413', 'CN', 'China',                               'https://flagcdn.com/h80/cn.png'),
        ('414', 'CN', 'China',                               'https://flagcdn.com/h80/cn.png'),
        ('416', 'TW', 'Taiwan',                              'https://flagcdn.com/h80/tw.png'),
        ('417', 'LK', 'Sri Lanka',                           'https://flagcdn.com/h80/lk.png'),
        ('419', 'IN', 'India',                               'https://flagcdn.com/h80/in.png'),
        ('422', 'IR', 'Iran',                                'https://flagcdn.com/h80/ir.png'),
        ('423', 'AZ', 'Azerbaijan',                          'https://flagcdn.com/h80/az.png'),
        ('425', 'IQ', 'Iraq',                                'https://flagcdn.com/h80/iq.png'),
        ('428', 'IL', 'Israel',                              'https://flagcdn.com/h80/il.png'),
        ('431', 'JP', 'Japan',                               'https://flagcdn.com/h80/jp.png'),
        ('432', 'JP', 'Japan',                               'https://flagcdn.com/h80/jp.png'),
        ('434', 'TM', 'Turkmenistan',                        'https://flagcdn.com/h80/tm.png'),
        ('436', 'KZ', 'Kazakhstan',                          'https://flagcdn.com/h80/kz.png'),
        ('437', 'UZ', 'Uzbekistan',                          'https://flagcdn.com/h80/uz.png'),
        ('438', 'JO', 'Jordan',                              'https://flagcdn.com/h80/jo.png'),
        ('440', 'KR', 'Korea',                               'https://flagcdn.com/h80/kr.png'),
        ('441', 'KR', 'Korea',                               'https://flagcdn.com/h80/kr.png'),
        ('443', 'PS', 'State of Palestine',                  'https://flagcdn.com/h80/ps.png'),
        ('445', 'KP', 'Democratic People''s Republic of Korea', 'https://flagcdn.com/h80/kp.png'),
        ('447', 'KW', 'Kuwait',                              'https://flagcdn.com/h80/kw.png'),
        ('450', 'LB', 'Lebanon',                             'https://flagcdn.com/h80/lb.png'),
        ('451', 'KG', 'Kyrgyz Republic',                     'https://flagcdn.com/h80/kg.png'),
        ('453', 'MO', 'Macao',                               'https://flagcdn.com/h80/mo.png'),
        ('455', 'MV', 'Maldives',                            'https://flagcdn.com/h80/mv.png'),
        ('457', 'MN', 'Mongolia',                            'https://flagcdn.com/h80/mn.png'),
        ('459', 'NP', 'Nepal',                               'https://flagcdn.com/h80/np.png'),
        ('461', 'OM', 'Oman',                                'https://flagcdn.com/h80/om.png'),
        ('463', 'PK', 'Pakistan',                            'https://flagcdn.com/h80/pk.png'),
        ('466', 'QA', 'Qatar',                               'https://flagcdn.com/h80/qa.png'),
        ('468', 'SY', 'Syrian Arab Republic',                'https://flagcdn.com/h80/sy.png'),
        ('470', 'AE', 'United Arab Emirates',                'https://flagcdn.com/h80/ae.png'),
        ('471', 'AE', 'United Arab Emirates',                'https://flagcdn.com/h80/ae.png'),
        ('472', 'TJ', 'Tajikistan',                          'https://flagcdn.com/h80/tj.png'),
        ('473', 'YE', 'Yemen',                               'https://flagcdn.com/h80/ye.png'),
        ('475', 'YE', 'Yemen',                               'https://flagcdn.com/h80/ye.png'),
        ('477', 'HK', 'Hong Kong',                           'https://flagcdn.com/h80/hk.png'),
        ('478', 'BA', 'Bosnia and Herzegovina',              'https://flagcdn.com/h80/ba.png'),
        ('503', 'AU', 'Australia',                           'https://flagcdn.com/h80/au.png'),
        ('506', 'MM', 'Myanmar',                             'https://flagcdn.com/h80/mm.png'),
        ('508', 'BN', 'Brunei Darussalam',                   'https://flagcdn.com/h80/bn.png'),
        ('510', 'FM', 'Micronesia',                          'https://flagcdn.com/h80/fm.png'),
        ('511', 'PW', 'Palau',                               'https://flagcdn.com/h80/pw.png'),
        ('512', 'NZ', 'New Zealand',                         'https://flagcdn.com/h80/nz.png'),
        ('514', 'KH', 'Cambodia',                            'https://flagcdn.com/h80/kh.png'),
        ('515', 'KH', 'Cambodia',                            'https://flagcdn.com/h80/kh.png'),
        ('516', 'CX', 'Christmas Island',                    'https://flagcdn.com/h80/cx.png'),
        ('518', 'CK', 'Cook Islands',                        'https://flagcdn.com/h80/ck.png'),
        ('520', 'FJ', 'Fiji',                                'https://flagcdn.com/h80/fj.png'),
        ('523', 'CC', 'Cocos (Keeling) Islands',             'https://flagcdn.com/h80/cc.png'),
        ('525', 'ID', 'Indonesia',                           'https://flagcdn.com/h80/id.png'),
        ('529', 'KI', 'Kiribati',                            'https://flagcdn.com/h80/ki.png'),
        ('531', 'LA', 'Lao People''s Democratic Republic',   'https://flagcdn.com/h80/la.png'),
        ('533', 'MY', 'Malaysia',                            'https://flagcdn.com/h80/my.png'),
        ('536', 'MP', 'Northern Mariana Islands',            'https://flagcdn.com/h80/mp.png'),
        ('538', 'MH', 'Marshall Islands',                    'https://flagcdn.com/h80/mh.png'),
        ('540', 'NC', 'New Caledonia',                       'https://flagcdn.com/h80/nc.png'),
        ('542', 'NU', 'Niue',                                'https://flagcdn.com/h80/nu.png'),
        ('544', 'NR', 'Nauru',                               'https://flagcdn.com/h80/nr.png'),
        ('546', 'PF', 'French Polynesia',                    'https://flagcdn.com/h80/pf.png'),
        ('548', 'PH', 'Philippines',                         'https://flagcdn.com/h80/ph.png'),
        ('550', 'TL', 'Timor-Leste',                         'https://flagcdn.com/h80/tl.png'),
        ('553', 'PG', 'Papua New Guinea',                    'https://flagcdn.com/h80/pg.png'),
        ('555', 'PN', 'Pitcairn Island',                     'https://flagcdn.com/h80/pn.png'),
        ('557', 'SB', 'Solomon Islands',                     'https://flagcdn.com/h80/sb.png'),
        ('559', 'AS', 'American Samoa',                      'https://flagcdn.com/h80/as.png'),
        ('561', 'WS', 'Samoa',                               'https://flagcdn.com/h80/ws.png'),
        ('563', 'SG', 'Singapore',                           'https://flagcdn.com/h80/sg.png'),
        ('564', 'SG', 'Singapore',                           'https://flagcdn.com/h80/sg.png'),
        ('565', 'SG', 'Singapore',                           'https://flagcdn.com/h80/sg.png'),
        ('566', 'SG', 'Singapore',                           'https://flagcdn.com/h80/sg.png'),
        ('567', 'TH', 'Thailand',                            'https://flagcdn.com/h80/th.png'),
        ('570', 'TO', 'Tonga',                               'https://flagcdn.com/h80/to.png'),
        ('572', 'TV', 'Tuvalu',                              'https://flagcdn.com/h80/tv.png'),
        ('574', 'VN', 'Viet Nam',                            'https://flagcdn.com/h80/vn.png'),
        ('576', 'VU', 'Vanuatu',                             'https://flagcdn.com/h80/vu.png'),
        ('577', 'VU', 'Vanuatu',                             'https://flagcdn.com/h80/vu.png'),
        ('578', 'WF', 'Wallis and Futuna Islands',           'https://flagcdn.com/h80/wf.png'),
        ('601', 'ZA', 'South Africa',                        'https://flagcdn.com/h80/za.png'),
        ('603', 'AO', 'Angola',                              'https://flagcdn.com/h80/ao.png'),
        ('605', 'DZ', 'Algeria',                             'https://flagcdn.com/h80/dz.png'),
        ('609', 'BI', 'Burundi',                             'https://flagcdn.com/h80/bi.png'),
        ('610', 'BJ', 'Benin',                               'https://flagcdn.com/h80/bj.png'),
        ('611', 'BW', 'Botswana',                            'https://flagcdn.com/h80/bw.png'),
        ('612', 'CF', 'Central African Republic',            'https://flagcdn.com/h80/cf.png'),
        ('613', 'CM', 'Cameroon',                            'https://flagcdn.com/h80/cm.png'),
        ('615', 'CG', 'Congo',                               'https://flagcdn.com/h80/cg.png'),
        ('616', 'KM', 'Comoros',                             'https://flagcdn.com/h80/km.png'),
        ('617', 'CV', 'Cabo Verde',                          'https://flagcdn.com/h80/cv.png'),
        ('619', 'CI', 'Ivory Coast',                         'https://flagcdn.com/h80/ci.png'),
        ('620', 'KM', 'Comoros',                             'https://flagcdn.com/h80/km.png'),
        ('621', 'DJ', 'Djibouti',                            'https://flagcdn.com/h80/dj.png'),
        ('622', 'EG', 'Egypt',                               'https://flagcdn.com/h80/eg.png'),
        ('624', 'ET', 'Ethiopia',                            'https://flagcdn.com/h80/et.png'),
        ('625', 'ER', 'Eritrea',                             'https://flagcdn.com/h80/er.png'),
        ('626', 'GA', 'Gabonese Republic',                   'https://flagcdn.com/h80/ga.png'),
        ('627', 'GH', 'Ghana',                               'https://flagcdn.com/h80/gh.png'),
        ('629', 'GM', 'Gambia',                              'https://flagcdn.com/h80/gm.png'),
        ('630', 'GW', 'Guinea-Bissau',                       'https://flagcdn.com/h80/gw.png'),
        ('631', 'GQ', 'Equatorial Guinea',                   'https://flagcdn.com/h80/gq.png'),
        ('632', 'GN', 'Guinea',                              'https://flagcdn.com/h80/gn.png'),
        ('633', 'BF', 'Burkina Faso',                        'https://flagcdn.com/h80/bf.png'),
        ('634', 'KE', 'Kenya',                               'https://flagcdn.com/h80/ke.png'),
        ('636', 'LR', 'Liberia',                             'https://flagcdn.com/h80/lr.png'),
        ('637', 'LR', 'Liberia',                             'https://flagcdn.com/h80/lr.png'),
        ('638', 'SS', 'South Sudan',                         'https://flagcdn.com/h80/ss.png'),
        ('642', 'LY', 'Libya',                               'https://flagcdn.com/h80/ly.png'),
        ('644', 'LS', 'Lesotho',                             'https://flagcdn.com/h80/ls.png'),
        ('645', 'MU', 'Mauritius',                           'https://flagcdn.com/h80/mu.png'),
        ('647', 'MG', 'Madagascar',                          'https://flagcdn.com/h80/mg.png'),
        ('649', 'ML', 'Mali',                                'https://flagcdn.com/h80/ml.png'),
        ('650', 'MZ', 'Mozambique',                          'https://flagcdn.com/h80/mz.png'),
        ('654', 'MR', 'Mauritania',                          'https://flagcdn.com/h80/mr.png'),
        ('655', 'MW', 'Malawi',                              'https://flagcdn.com/h80/mw.png'),
        ('656', 'NE', 'Niger',                               'https://flagcdn.com/h80/ne.png'),
        ('657', 'NG', 'Nigeria',                             'https://flagcdn.com/h80/ng.png'),
        ('659', 'NA', 'Namibia',                             'https://flagcdn.com/h80/na.png'),
        ('660', 'RE', 'Reunion',                             'https://flagcdn.com/h80/re.png'),
        ('661', 'RW', 'Rwanda',                              'https://flagcdn.com/h80/rw.png'),
        ('662', 'SD', 'Sudan',                               'https://flagcdn.com/h80/sd.png'),
        ('663', 'SN', 'Senegal',                             'https://flagcdn.com/h80/sn.png'),
        ('664', 'SC', 'Seychelles',                          'https://flagcdn.com/h80/sc.png'),
        ('665', 'SH', 'Saint Helena',                        'https://flagcdn.com/h80/sh.png'),
        ('666', 'SO', 'Somali Democratic Republic',          'https://flagcdn.com/h80/so.png'),
        ('667', 'SL', 'Sierra Leone',                        'https://flagcdn.com/h80/sl.png'),
        ('668', 'ST', 'Sao Tome and Principe',               'https://flagcdn.com/h80/st.png'),
        ('669', 'SZ', 'Swaziland',                           'https://flagcdn.com/h80/sz.png'),
        ('670', 'TD', 'Chad',                                'https://flagcdn.com/h80/td.png'),
        ('671', 'TG', 'Togolese Republic',                   'https://flagcdn.com/h80/tg.png'),
        ('672', 'TN', 'Tunisian Republic',                   'https://flagcdn.com/h80/tn.png'),
        ('674', 'TZ', 'Tanzania',                            'https://flagcdn.com/h80/tz.png'),
        ('675', 'UG', 'Uganda',                              'https://flagcdn.com/h80/ug.png'),
        ('676', 'CD', 'Democratic Republic of the Congo',   'https://flagcdn.com/h80/cd.png'),
        ('677', 'TZ', 'Tanzania',                            'https://flagcdn.com/h80/tz.png'),
        ('678', 'ZM', 'Zambia',                              'https://flagcdn.com/h80/zm.png'),
        ('679', 'ZW', 'Zimbabwe',                            'https://flagcdn.com/h80/zw.png'),
        ('701', 'AR', 'Argentine Republic',                  'https://flagcdn.com/h80/ar.png'),
        ('710', 'BR', 'Brazil',                              'https://flagcdn.com/h80/br.png'),
        ('720', 'BO', 'Bolivia',                             'https://flagcdn.com/h80/bo.png'),
        ('725', 'CL', 'Chile',                               'https://flagcdn.com/h80/cl.png'),
        ('730', 'CO', 'Colombia',                            'https://flagcdn.com/h80/co.png'),
        ('735', 'EC', 'Ecuador',                             'https://flagcdn.com/h80/ec.png'),
        ('740', 'FK', 'Falkland Islands',                    'https://flagcdn.com/h80/fk.png'),
        ('745', 'GF', 'Guiana',                              'https://flagcdn.com/h80/gf.png'),
        ('750', 'GY', 'Guyana',                              'https://flagcdn.com/h80/gy.png'),
        ('755', 'PY', 'Paraguay',                            'https://flagcdn.com/h80/py.png'),
        ('760', 'PE', 'Peru',                                'https://flagcdn.com/h80/pe.png'),
        ('765', 'SR', 'Suriname',                            'https://flagcdn.com/h80/sr.png'),
        ('770', 'UY', 'Uruguay',                             'https://flagcdn.com/h80/uy.png'),
        ('775', 'VE', 'Venezuela',                           'https://flagcdn.com/h80/ve.png')
)
UPDATE ship_positions sp
SET metadata = COALESCE(sp.metadata, '{}'::jsonb)
    || jsonb_build_object(
        'flag_country', mc.country_name,
        'flag_url',     mc.flag_url
    )
FROM mid_countries mc
WHERE LEFT(sp.mmsi, 3) = mc.mid
  AND (sp.metadata IS NULL OR sp.metadata->>'flag_country' IS NULL);
