{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracking-platform.configMapName" . }}
  labels:
    {{- include "tracking-platform.labels" . | nindent 4 }}
{{- if .Values.config.data }}
data:
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
{{- end }}
