{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracking-platform.secretName" . }}
  labels:
    {{- include "tracking-platform.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets.stringData }}
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
