server:
  port: ${SERVER_PORT:8084}

spring:
  kafka:
    bootstrap-servers: ${TRACKING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tracking}
    username: ${SPRING_DATASOURCE_USERNAME:tracking}
    password: ${SPRING_DATASOURCE_PASSWORD:tracking}
