gateway:
  service:
    type: LoadBalancer
  replicaCount: 2
  pdb:
    enabled: true

ingress:
  enabled: true
  hosts:
    - host: tracking.stg.local
      paths:
        - path: /
          pathType: Prefix

auth:
  replicaCount: 2
  pdb:
    enabled: true

ingestion:
  replicaCount: 2
  pdb:
    enabled: true

processing:
  replicaCount: 2
  pdb:
    enabled: true

storage:
  replicaCount: 2
  pdb:
    enabled: true

broadcaster:
  replicaCount: 2
  pdb:
    enabled: true
