package com.tracking.processing.enrich

/**
 * Resolves the flag country of a vessel from its MMSI using the
 * Maritime Identification Digits (first 3 digits of MMSI).
 *
 * Data source: ITU MID table (mids.json at repo root).
 * MID_TABLE is embedded to avoid runtime I/O and extra dependencies,
 * consistent with the IcaoCountryResolver pattern.
 */
public class MidCountryResolver {

    public fun resolve(mmsi: String): MidCountryInfo? {
        val mid = extractMid(mmsi) ?: return null
        val entry = MID_TABLE[mid] ?: return null
        return MidCountryInfo(
            countryCode = entry.iso2,
            countryName = entry.countryName,
            flagUrl = buildFlagUrl(entry.iso2),
        )
    }

    private fun extractMid(mmsi: String): String? {
        val digits = mmsi.trim()
        if (digits.length != MMSI_LENGTH) return null
        if (!digits.all { it.isDigit() }) return null
        return digits.substring(0, MID_LENGTH)
    }

    private fun buildFlagUrl(countryCode: String): String =
        "$FLAG_CDN_BASE_URL/${countryCode.lowercase()}.png"

    private companion object {
        private const val MMSI_LENGTH = 9
        private const val MID_LENGTH = 3
        private const val FLAG_CDN_BASE_URL = "https://flagcdn.com/h80"

        // Sourced from ITU MID table (mids.json). Stable data — ITU updates very rarely.
        private val MID_TABLE: Map<String, MidEntry> = mapOf(
            "201" to MidEntry("AL", "ALB", "", "Albania"),
            "202" to MidEntry("AD", "AND", "", "Andorra"),
            "203" to MidEntry("AT", "AUT", "", "Austria"),
            "204" to MidEntry("PT", "PRT", "PT-20", "Azores"),
            "205" to MidEntry("BE", "BEL", "", "Belgium"),
            "206" to MidEntry("BY", "BLR", "", "Belarus"),
            "207" to MidEntry("BG", "BGR", "", "Bulgaria"),
            "208" to MidEntry("VA", "VAT", "", "Vatican City State"),
            "209" to MidEntry("CY", "CYP", "", "Cyprus"),
            "210" to MidEntry("CY", "CYP", "", "Cyprus"),
            "211" to MidEntry("DE", "DEU", "", "Germany"),
            "212" to MidEntry("CY", "CYP", "", "Cyprus"),
            "213" to MidEntry("GE", "GEO", "", "Georgia"),
            "214" to MidEntry("MD", "MDA", "", "Moldova"),
            "215" to MidEntry("MT", "MLT", "", "Malta"),
            "216" to MidEntry("AM", "ARM", "", "Armenia"),
            "218" to MidEntry("DE", "DEU", "", "Germany"),
            "219" to MidEntry("DK", "DNK", "", "Denmark"),
            "220" to MidEntry("DK", "DNK", "", "Denmark"),
            "224" to MidEntry("ES", "ESP", "", "Spain"),
            "225" to MidEntry("ES", "ESP", "", "Spain"),
            "226" to MidEntry("FR", "FRA", "", "France"),
            "227" to MidEntry("FR", "FRA", "", "France"),
            "228" to MidEntry("FR", "FRA", "", "France"),
            "229" to MidEntry("MT", "MLT", "", "Malta"),
            "230" to MidEntry("FI", "FIN", "", "Finland"),
            "231" to MidEntry("FO", "FRO", "", "Faroe Islands"),
            "232" to MidEntry("GB", "GBR", "", "United Kingdom"),
            "233" to MidEntry("GB", "GBR", "", "United Kingdom"),
            "234" to MidEntry("GB", "GBR", "", "United Kingdom"),
            "235" to MidEntry("GB", "GBR", "", "United Kingdom"),
            "236" to MidEntry("GI", "GIB", "", "Gibraltar"),
            "237" to MidEntry("GR", "GRC", "", "Greece"),
            "238" to MidEntry("HR", "HRV", "", "Croatia"),
            "239" to MidEntry("GR", "GRC", "", "Greece"),
            "240" to MidEntry("GR", "GRC", "", "Greece"),
            "241" to MidEntry("GR", "GRC", "", "Greece"),
            "242" to MidEntry("MA", "MAR", "", "Morocco"),
            "243" to MidEntry("HU", "HUN", "", "Hungary"),
            "244" to MidEntry("NL", "NLD", "", "Netherlands"),
            "245" to MidEntry("NL", "NLD", "", "Netherlands"),
            "246" to MidEntry("NL", "NLD", "", "Netherlands"),
            "247" to MidEntry("IT", "ITA", "", "Italy"),
            "248" to MidEntry("MT", "MLT", "", "Malta"),
            "249" to MidEntry("MT", "MLT", "", "Malta"),
            "250" to MidEntry("IE", "IRL", "", "Ireland"),
            "251" to MidEntry("IS", "ISL", "", "Iceland"),
            "252" to MidEntry("LI", "LIE", "", "Liechtenstein"),
            "253" to MidEntry("LU", "LUX", "", "Luxembourg"),
            "254" to MidEntry("MC", "MCO", "", "Monaco"),
            "255" to MidEntry("PT", "PRT", "PT-30", "Madeira"),
            "256" to MidEntry("MT", "MLT", "", "Malta"),
            "257" to MidEntry("NO", "NOR", "", "Norway"),
            "258" to MidEntry("NO", "NOR", "", "Norway"),
            "259" to MidEntry("NO", "NOR", "", "Norway"),
            "261" to MidEntry("PL", "POL", "", "Poland"),
            "262" to MidEntry("ME", "MNE", "", "Montenegro"),
            "263" to MidEntry("PT", "PRT", "", "Portugal"),
            "264" to MidEntry("RO", "ROU", "", "Romania"),
            "265" to MidEntry("SE", "SWE", "", "Sweden"),
            "266" to MidEntry("SE", "SWE", "", "Sweden"),
            "267" to MidEntry("SK", "SVK", "", "Slovak Republic"),
            "268" to MidEntry("SM", "SMR", "", "San Marino"),
            "269" to MidEntry("CH", "CHE", "", "Switzerland"),
            "270" to MidEntry("CZ", "CZE", "", "Czech Republic"),
            "271" to MidEntry("TR", "TUR", "", "Turkey"),
            "272" to MidEntry("UA", "UKR", "", "Ukraine"),
            "273" to MidEntry("RU", "RUS", "", "Russia"),
            "274" to MidEntry("MK", "MKD", "", "Macedonia"),
            "275" to MidEntry("LV", "LVA", "", "Latvia"),
            "276" to MidEntry("EE", "EST", "", "Estonia"),
            "277" to MidEntry("LT", "LTU", "", "Lithuania"),
            "278" to MidEntry("SI", "SVN", "", "Slovenia"),
            "279" to MidEntry("RS", "SRB", "", "Serbia"),
            "301" to MidEntry("AI", "AIA", "", "Anguilla"),
            "303" to MidEntry("US", "USA", "US-AK", "Alaska"),
            "304" to MidEntry("AG", "ATG", "", "Antigua and Barbuda"),
            "305" to MidEntry("AG", "ATG", "", "Antigua and Barbuda"),
            "306" to MidEntry("CW", "CUW", "", "Antilles"),
            "307" to MidEntry("AW", "ABW", "", "Aruba"),
            "308" to MidEntry("BS", "BHS", "", "Bahamas"),
            "309" to MidEntry("BS", "BHS", "", "Bahamas"),
            "310" to MidEntry("BM", "BMU", "", "Bermuda"),
            "311" to MidEntry("BS", "BMU", "", "Bahamas"),
            "312" to MidEntry("BZ", "BLZ", "", "Belize"),
            "314" to MidEntry("BB", "BRB", "", "Barbados"),
            "316" to MidEntry("CA", "CAN", "", "Canada"),
            "319" to MidEntry("KY", "CYM", "", "Cayman Islands"),
            "321" to MidEntry("CR", "CRI", "", "Costa Rica"),
            "323" to MidEntry("CU", "CUB", "", "Cuba"),
            "325" to MidEntry("DM", "DMA", "", "Dominica"),
            "327" to MidEntry("DO", "DOM", "", "Dominican Republic"),
            "329" to MidEntry("GP", "GLP", "", "Guadeloupe"),
            "330" to MidEntry("GD", "GRD", "", "Grenada"),
            "331" to MidEntry("GL", "GRL", "", "Greenland"),
            "332" to MidEntry("GT", "GTM", "", "Guatemala"),
            "334" to MidEntry("HN", "HND", "", "Honduras"),
            "336" to MidEntry("HT", "HTI", "", "Haiti"),
            "338" to MidEntry("US", "USA", "", "United States of America"),
            "339" to MidEntry("JM", "JAM", "", "Jamaica"),
            "341" to MidEntry("KN", "KNA", "", "Saint Kitts and Nevis"),
            "343" to MidEntry("LC", "LCA", "", "Saint Lucia"),
            "345" to MidEntry("MX", "MEX", "", "Mexico"),
            "347" to MidEntry("MQ", "MTQ", "", "Martinique"),
            "348" to MidEntry("MS", "MSR", "", "Montserrat"),
            "350" to MidEntry("NI", "NIC", "", "Nicaragua"),
            "351" to MidEntry("PA", "PAN", "", "Panama"),
            "352" to MidEntry("PA", "PAN", "", "Panama"),
            "353" to MidEntry("PA", "PAN", "", "Panama"),
            "354" to MidEntry("PA", "PAN", "", "Panama"),
            "355" to MidEntry("PA", "PAN", "", "Panama"),
            "356" to MidEntry("PA", "PAN", "", "Panama"),
            "357" to MidEntry("PA", "PAN", "", "Panama"),
            "358" to MidEntry("PR", "PRI", "", "Puerto Rico"),
            "359" to MidEntry("SV", "SLV", "", "El Salvador"),
            "361" to MidEntry("PM", "SPM", "", "Saint Pierre and Miquelon"),
            "362" to MidEntry("TT", "TTO", "", "Trinidad and Tobago"),
            "364" to MidEntry("TC", "TCA", "", "Turks and Caicos Islands"),
            "366" to MidEntry("US", "USA", "", "United States of America"),
            "367" to MidEntry("US", "USA", "", "United States of America"),
            "368" to MidEntry("US", "USA", "", "United States of America"),
            "369" to MidEntry("US", "USA", "", "United States of America"),
            "370" to MidEntry("PA", "PAN", "", "Panama"),
            "371" to MidEntry("PA", "PAN", "", "Panama"),
            "372" to MidEntry("PA", "PAN", "", "Panama"),
            "373" to MidEntry("PA", "PAN", "", "Panama"),
            "374" to MidEntry("PA", "PAN", "", "Panama"),
            "375" to MidEntry("VC", "VCT", "", "Saint Vincent and the Grenadines"),
            "376" to MidEntry("VC", "VCT", "", "Saint Vincent and the Grenadines"),
            "377" to MidEntry("VC", "VCT", "", "Saint Vincent and the Grenadines"),
            "378" to MidEntry("VG", "VGB", "", "British Virgin Islands"),
            "379" to MidEntry("VI", "VIR", "", "United States Virgin Islands"),
            "401" to MidEntry("AF", "AFG", "", "Afghanistan"),
            "403" to MidEntry("SA", "SAU", "", "Saudi Arabia"),
            "405" to MidEntry("BD", "BGD", "", "Bangladesh"),
            "408" to MidEntry("BH", "BHR", "", "Bahrain"),
            "410" to MidEntry("BT", "BTN", "", "Bhutan"),
            "412" to MidEntry("CN", "CHN", "", "China"),
            "413" to MidEntry("CN", "CHN", "", "China"),
            "414" to MidEntry("CN", "CHN", "", "China"),
            "416" to MidEntry("TW", "TWN", "", "Taiwan"),
            "417" to MidEntry("LK", "LKA", "", "Sri Lanka"),
            "419" to MidEntry("IN", "IND", "", "India"),
            "422" to MidEntry("IR", "IRN", "", "Iran"),
            "423" to MidEntry("AZ", "AZE", "", "Azerbaijan"),
            "425" to MidEntry("IQ", "IRQ", "", "Iraq"),
            "428" to MidEntry("IL", "ISR", "", "Israel"),
            "431" to MidEntry("JP", "JPN", "", "Japan"),
            "432" to MidEntry("JP", "JPN", "", "Japan"),
            "434" to MidEntry("TM", "TKM", "", "Turkmenistan"),
            "436" to MidEntry("KZ", "KAZ", "", "Kazakhstan"),
            "437" to MidEntry("UZ", "UZB", "", "Uzbekistan"),
            "438" to MidEntry("JO", "JOR", "", "Jordan"),
            "440" to MidEntry("KR", "KOR", "", "Korea"),
            "441" to MidEntry("KR", "KOR", "", "Korea"),
            "443" to MidEntry("PS", "PSE", "", "State of Palestine"),
            "445" to MidEntry("KP", "PRK", "", "Democratic People's Republic of Korea"),
            "447" to MidEntry("KW", "KWT", "", "Kuwait"),
            "450" to MidEntry("LB", "LBN", "", "Lebanon"),
            "451" to MidEntry("KG", "KGZ", "", "Kyrgyz Republic"),
            "453" to MidEntry("MO", "MAC", "", "Macao"),
            "455" to MidEntry("MV", "MDV", "", "Maldives"),
            "457" to MidEntry("MN", "MNG", "", "Mongolia"),
            "459" to MidEntry("NP", "NPL", "", "Nepal"),
            "461" to MidEntry("OM", "OMN", "", "Oman"),
            "463" to MidEntry("PK", "PAK", "", "Pakistan"),
            "466" to MidEntry("QA", "QAT", "", "Qatar (State of)"),
            "468" to MidEntry("SY", "SYR", "", "Syrian Arab Republic"),
            "470" to MidEntry("AE", "ARE", "", "United Arab Emirates"),
            "471" to MidEntry("AE", "ARE", "", "United Arab Emirates"),
            "472" to MidEntry("TJ", "TJK", "", "Tajikistan"),
            "473" to MidEntry("YE", "YEM", "", "Yemen"),
            "475" to MidEntry("YE", "YEM", "", "Yemen"),
            "477" to MidEntry("HK", "HKG", "", "Hong Kong"),
            "478" to MidEntry("BA", "BIH", "", "Bosnia and Herzegovina"),
            "501" to MidEntry("FR", "FRA", "AQ", "Adelie Land"),
            "503" to MidEntry("AU", "AUS", "", "Australia"),
            "506" to MidEntry("MM", "MMR", "", "Myanmar"),
            "508" to MidEntry("BN", "BRN", "", "Brunei Darussalam"),
            "510" to MidEntry("FM", "FSM", "", "Micronesia"),
            "511" to MidEntry("PW", "PLW", "", "Palau"),
            "512" to MidEntry("NZ", "NZL", "", "New Zealand"),
            "514" to MidEntry("KH", "KHM", "", "Cambodia"),
            "515" to MidEntry("KH", "KHM", "", "Cambodia"),
            "516" to MidEntry("CX", "CXR", "", "Christmas Island"),
            "518" to MidEntry("CK", "COK", "", "Cook Islands"),
            "520" to MidEntry("FJ", "FJI", "", "Fiji"),
            "523" to MidEntry("CC", "CCK", "", "Cocos (Keeling) Islands"),
            "525" to MidEntry("ID", "IDN", "", "Indonesia"),
            "529" to MidEntry("KI", "KIR", "", "Kiribati"),
            "531" to MidEntry("LA", "LAO", "", "Lao People's Democratic Republic"),
            "533" to MidEntry("MY", "MYS", "", "Malaysia"),
            "536" to MidEntry("MP", "MNP", "", "Northern Mariana Islands"),
            "538" to MidEntry("MH", "MHL", "", "Marshall Islands"),
            "540" to MidEntry("NC", "NCL", "", "New Caledonia"),
            "542" to MidEntry("NU", "NIU", "", "Niue"),
            "544" to MidEntry("NR", "NRU", "", "Nauru"),
            "546" to MidEntry("PF", "PYF", "", "French Polynesia"),
            "548" to MidEntry("PH", "PHL", "", "Philippines"),
            "550" to MidEntry("TL", "TLS", "", "Timor-Leste (Democratic Republic of)"),
            "553" to MidEntry("PG", "PNG", "", "Papua New Guinea"),
            "555" to MidEntry("PN", "PCN", "", "Pitcairn Island"),
            "557" to MidEntry("SB", "SLB", "", "Solomon Islands"),
            "559" to MidEntry("AS", "ASM", "", "American Samoa"),
            "561" to MidEntry("WS", "WSM", "", "Samoa"),
            "563" to MidEntry("SG", "SGP", "", "Singapore"),
            "564" to MidEntry("SG", "SGP", "", "Singapore"),
            "565" to MidEntry("SG", "SGP", "", "Singapore"),
            "566" to MidEntry("SG", "SGP", "", "Singapore"),
            "567" to MidEntry("TH", "THA", "", "Thailand"),
            "570" to MidEntry("TO", "TON", "", "Tonga"),
            "572" to MidEntry("TV", "TUV", "", "Tuvalu"),
            "574" to MidEntry("VN", "VNM", "", "Viet Nam"),
            "576" to MidEntry("VU", "VUT", "", "Vanuatu"),
            "577" to MidEntry("VU", "VUT", "", "Vanuatu"),
            "578" to MidEntry("WF", "WLF", "", "Wallis and Futuna Islands"),
            "601" to MidEntry("ZA", "ZAF", "", "South Africa"),
            "603" to MidEntry("AO", "AGO", "", "Angola"),
            "605" to MidEntry("DZ", "DZA", "", "Algeria"),
            "607" to MidEntry("FR", "FRA", "TF", "Saint Paul and Amsterdam Islands"),
            "608" to MidEntry("GB", "GBR", "AC", "Ascension Island"),
            "609" to MidEntry("BI", "BDI", "", "Burundi"),
            "610" to MidEntry("BJ", "BEN", "", "Benin"),
            "611" to MidEntry("BW", "BWA", "", "Botswana"),
            "612" to MidEntry("CF", "CAF", "", "Central African Republic"),
            "613" to MidEntry("CM", "CMR", "", "Cameroon"),
            "615" to MidEntry("CG", "COG", "", "Congo"),
            "616" to MidEntry("KM", "COM", "", "Comoros"),
            "617" to MidEntry("CV", "CPV", "", "Cabo Verde"),
            "618" to MidEntry("FR", "FRA", "TF", "Crozet Archipelago"),
            "619" to MidEntry("CI", "CIV", "", "Ivory Coast"),
            "620" to MidEntry("KM", "COM", "", "Comoros"),
            "621" to MidEntry("DJ", "DJI", "", "Djibouti"),
            "622" to MidEntry("EG", "EGY", "", "Egypt"),
            "624" to MidEntry("ET", "ETH", "", "Ethiopia"),
            "625" to MidEntry("ER", "ERI", "", "Eritrea"),
            "626" to MidEntry("GA", "GAB", "", "Gabonese Republic"),
            "627" to MidEntry("GH", "GHA", "", "Ghana"),
            "629" to MidEntry("GM", "GMB", "", "Gambia"),
            "630" to MidEntry("GW", "GNB", "", "Guinea-Bissau"),
            "631" to MidEntry("GQ", "GNQ", "", "Equatorial Guinea"),
            "632" to MidEntry("GN", "GIN", "", "Guinea"),
            "633" to MidEntry("BF", "BFA", "", "Burkina Faso"),
            "634" to MidEntry("KE", "KEN", "", "Kenya"),
            "635" to MidEntry("FR", "FRA", "TF", "Kerguelen Islands"),
            "636" to MidEntry("LR", "LBR", "", "Liberia"),
            "637" to MidEntry("LR", "LBR", "", "Liberia"),
            "638" to MidEntry("SS", "SSD", "", "South Sudan"),
            "642" to MidEntry("LY", "LBY", "", "Libya"),
            "644" to MidEntry("LS", "LSO", "", "Lesotho"),
            "645" to MidEntry("MU", "MUS", "", "Mauritius"),
            "647" to MidEntry("MG", "MDG", "", "Madagascar"),
            "649" to MidEntry("ML", "MLI", "", "Mali"),
            "650" to MidEntry("MZ", "MOZ", "", "Mozambique"),
            "654" to MidEntry("MR", "MRT", "", "Mauritania"),
            "655" to MidEntry("MW", "MWI", "", "Malawi"),
            "656" to MidEntry("NE", "NER", "", "Niger"),
            "657" to MidEntry("NG", "NGA", "", "Nigeria"),
            "659" to MidEntry("NA", "NAM", "", "Namibia"),
            "660" to MidEntry("RE", "REU", "", "Reunion"),
            "661" to MidEntry("RW", "RWA", "", "Rwanda"),
            "662" to MidEntry("SD", "SDN", "", "Sudan"),
            "663" to MidEntry("SN", "SEN", "", "Senegal"),
            "664" to MidEntry("SC", "SYC", "", "Seychelles"),
            "665" to MidEntry("SH", "SHN", "", "Saint Helena"),
            "666" to MidEntry("SO", "SOM", "", "Somali Democratic Republic"),
            "667" to MidEntry("SL", "SLE", "", "Sierra Leone"),
            "668" to MidEntry("ST", "STP", "", "Sao Tome and Principe"),
            "669" to MidEntry("SZ", "SWZ", "", "Swaziland"),
            "670" to MidEntry("TD", "TCD", "", "Chad"),
            "671" to MidEntry("TG", "TGO", "", "Togolese Republic"),
            "672" to MidEntry("TN", "TUN", "", "Tunisian Republic"),
            "674" to MidEntry("TZ", "TZA", "", "Tanzania"),
            "675" to MidEntry("UG", "UGA", "", "Uganda"),
            "676" to MidEntry("CD", "COD", "", "Democratic Republic of the Congo"),
            "677" to MidEntry("TZ", "TZA", "", "Tanzania"),
            "678" to MidEntry("ZM", "ZMB", "", "Zambia"),
            "679" to MidEntry("ZW", "ZWE", "", "Zimbabwe"),
            "701" to MidEntry("AR", "ARG", "", "Argentine Republic"),
            "710" to MidEntry("BR", "BRA", "", "Brazil"),
            "720" to MidEntry("BO", "BOL", "", "Bolivia"),
            "725" to MidEntry("CL", "CHL", "", "Chile"),
            "730" to MidEntry("CO", "COL", "", "Colombia"),
            "735" to MidEntry("EC", "ECU", "", "Ecuador"),
            "740" to MidEntry("FK", "FLK", "", "Falkland Islands"),
            "745" to MidEntry("GF", "GUF", "", "Guiana"),
            "750" to MidEntry("GY", "GUY", "", "Guyana"),
            "755" to MidEntry("PY", "PRY", "", "Paraguay"),
            "760" to MidEntry("PE", "PER", "", "Peru"),
            "765" to MidEntry("SR", "SUR", "", "Suriname"),
            "770" to MidEntry("UY", "URY", "", "Uruguay"),
            "775" to MidEntry("VE", "VEN", "", "Venezuela"),
        )
    }
}

public data class MidCountryInfo(
    val countryCode: String,   // ISO 3166-1 alpha-2 (e.g. "VN")
    val countryName: String,   // Full name (e.g. "Viet Nam")
    val flagUrl: String,       // CDN URL to flag image
)

internal data class MidEntry(
    val iso2: String,
    val iso3: String,
    val subdivision: String,
    val countryName: String,
)
