spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: ${TRACKING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest

tracking:
  processing:
    consumer:
      group-id: service-processing-local
    producer:
      publish-timeout-millis: 1500
    enrichment:
      planespotters:
        enabled: false
