server:
  port: ${SERVER_PORT:8085}

spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: ${TRACKING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      auto-offset-reset: earliest

tracking:
  processing:
    consumer:
      group-id: service-processing-local
    enrichment:
      planespotters:
        enabled: false
