gateway:
  service:
    type: NodePort
  replicaCount: 1
  pdb:
    enabled: false
  hpa:
    enabled: false

ingress:
  enabled: true
  hosts:
    - host: tracking.dev.local
      paths:
        - path: /
          pathType: Prefix

auth:
  replicaCount: 1
  pdb:
    enabled: false
  hpa:
    enabled: false

ingestion:
  replicaCount: 1
  pdb:
    enabled: false
  hpa:
    enabled: false

processing:
  replicaCount: 1
  pdb:
    enabled: false
  hpa:
    enabled: false

storage:
  replicaCount: 1
  pdb:
    enabled: false
  hpa:
    enabled: false

broadcaster:
  replicaCount: 1
  pdb:
    enabled: false
  hpa:
    enabled: false
