name: tracking-connectors

services:
  adsb-hckt-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-adsb-hckt-connector
    restart: unless-stopped
    command: [ "adsb-hckt" ]
    env_file:
      - ../connectors/env/hckt.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking-net

  adsbx-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-adsbx-connector
    restart: unless-stopped
    command: [ "adsbx" ]
    env_file:
      - ../connectors/env/adsbx.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: "1gb"
    networks:
      - tracking-net

  fr24-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-fr24-connector
    restart: unless-stopped
    command: [ "fr24" ]
    env_file:
      - ../connectors/env/fr24.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking-net

  radarbox-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-radarbox-connector
    restart: unless-stopped
    command: [ "radarbox" ]
    env_file:
      - ../connectors/env/radarbox.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking-net

  chinaport-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-chinaport-connector
    restart: unless-stopped
    command: [ "chinaport" ]
    env_file:
      - ../connectors/env/chinaport.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking-net

  aisstream-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-aisstream-connector
    restart: unless-stopped
    command: [ "aisstream" ]
    env_file:
      - ../connectors/env/aisstream.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking-net

  ais-signalr-connector:
    build:
      context: ..
      dockerfile: connectors/Dockerfile
    container_name: tracking-ais-signalr-connector
    restart: unless-stopped
    command: [ "signalr" ]
    env_file:
      - ../connectors/env/ais_signalr.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking-net

networks:
  tracking-net:
    name: tracking-net
    external: true # Đã được tạo bởi infrastructure/docker-compose.yml
